///////////////////////////////////////////////////////////////////////////////////
// The MIT License (MIT)
//
// Copyright (c) 2017 Tarek Sherif
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
///////////////////////////////////////////////////////////////////////////////////

#include <stdio.h>
#include <string.h>
#include <X11/Xlib.h>
#include "xogl.h"
#include "xogl-context.h"

void (* glCullFace)(GLenum mode);
void (* glFrontFace)(GLenum mode);
void (* glHint)(GLenum target, GLenum mode);
void (* glLineWidth)(GLfloat width);
void (* glPointSize)(GLfloat size);
void (* glPolygonMode)(GLenum face, GLenum mode);
void (* glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
void (* glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
void (* glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void (* glTexParameteri)(GLenum target, GLenum pname, GLint param);
void (* glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
void (* glTexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
void (* glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void (* glDrawBuffer)(GLenum buf);
void (* glClear)(GLbitfield mask);
void (* glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (* glClearStencil)(GLint s);
void (* glClearDepth)(GLdouble depth);
void (* glStencilMask)(GLuint mask);
void (* glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void (* glDepthMask)(GLboolean flag);
void (* glDisable)(GLenum cap);
void (* glEnable)(GLenum cap);
void (* glFinish)(void);
void (* glFlush)(void);
void (* glBlendFunc)(GLenum sfactor, GLenum dfactor);
void (* glLogicOp)(GLenum opcode);
void (* glStencilFunc)(GLenum func, GLint ref, GLuint mask);
void (* glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
void (* glDepthFunc)(GLenum func);
void (* glPixelStoref)(GLenum pname, GLfloat param);
void (* glPixelStorei)(GLenum pname, GLint param);
void (* glReadBuffer)(GLenum src);
void (* glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
void (* glGetBooleanv)(GLenum pname, GLboolean *data);
void (* glGetDoublev)(GLenum pname, GLdouble *data);
GLenum (* glGetError)(void);
void (* glGetFloatv)(GLenum pname, GLfloat *data);
void (* glGetIntegerv)(GLenum pname, GLint *data);
void (* glGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
void (* glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (* glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
void (* glGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
void (* glGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
GLboolean (* glIsEnabled)(GLenum cap);
void (* glDepthRange)(GLdouble near, GLdouble far);
void (* glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);
void (* glDrawArrays)(GLenum mode, GLint first, GLsizei count);
void (* glDrawElements)(GLenum mode, GLsizei count, GLenum type, const void *indices);
void (* glGetPointerv)(GLenum pname, void **params);
void (* glPolygonOffset)(GLfloat factor, GLfloat units);
void (* glCopyTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
void (* glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void (* glCopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void (* glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
void (* glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void (* glBindTexture)(GLenum target, GLuint texture);
void (* glDeleteTextures)(GLsizei n, const GLuint *textures);
void (* glGenTextures)(GLsizei n, GLuint *textures);
GLboolean (* glIsTexture)(GLuint texture);
void (* glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
void (* glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
void (* glTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void (* glCopyTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glActiveTexture)(GLenum texture);
void (* glSampleCoverage)(GLfloat value, GLboolean invert);
void (* glCompressedTexImage3D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
void (* glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void (* glCompressedTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
void (* glCompressedTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void (* glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void (* glCompressedTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
void (* glGetCompressedTexImage)(GLenum target, GLint level, void *img);
void (* glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void (* glMultiDrawArrays)(GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
void (* glMultiDrawElements)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
void (* glPointParameterf)(GLenum pname, GLfloat param);
void (* glPointParameterfv)(GLenum pname, const GLfloat *params);
void (* glPointParameteri)(GLenum pname, GLint param);
void (* glPointParameteriv)(GLenum pname, const GLint *params);
void (* glBlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (* glBlendEquation)(GLenum mode);
void (* glGenQueries)(GLsizei n, GLuint *ids);
void (* glDeleteQueries)(GLsizei n, const GLuint *ids);
GLboolean (* glIsQuery)(GLuint id);
void (* glBeginQuery)(GLenum target, GLuint id);
void (* glEndQuery)(GLenum target);
void (* glGetQueryiv)(GLenum target, GLenum pname, GLint *params);
void (* glGetQueryObjectiv)(GLuint id, GLenum pname, GLint *params);
void (* glGetQueryObjectuiv)(GLuint id, GLenum pname, GLuint *params);
void (* glBindBuffer)(GLenum target, GLuint buffer);
void (* glDeleteBuffers)(GLsizei n, const GLuint *buffers);
void (* glGenBuffers)(GLsizei n, GLuint *buffers);
GLboolean (* glIsBuffer)(GLuint buffer);
void (* glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void (* glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
void (* glGetBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, void *data);
GLboolean (* glUnmapBuffer)(GLenum target);
void (* glGetBufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (* glGetBufferPointerv)(GLenum target, GLenum pname, void **params);
void (* glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
void (* glDrawBuffers)(GLsizei n, const GLenum *bufs);
void (* glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void (* glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
void (* glStencilMaskSeparate)(GLenum face, GLuint mask);
void (* glAttachShader)(GLuint program, GLuint shader);
void (* glBindAttribLocation)(GLuint program, GLuint index, const GLchar *name);
void (* glCompileShader)(GLuint shader);
GLuint (* glCreateProgram)(void);
GLuint (* glCreateShader)(GLenum type);
void (* glDeleteProgram)(GLuint program);
void (* glDeleteShader)(GLuint shader);
void (* glDetachShader)(GLuint program, GLuint shader);
void (* glDisableVertexAttribArray)(GLuint index);
void (* glEnableVertexAttribArray)(GLuint index);
void (* glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (* glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (* glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
GLint (* glGetAttribLocation)(GLuint program, const GLchar *name);
void (* glGetProgramiv)(GLuint program, GLenum pname, GLint *params);
void (* glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (* glGetShaderiv)(GLuint shader, GLenum pname, GLint *params);
void (* glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (* glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
GLint (* glGetUniformLocation)(GLuint program, const GLchar *name);
void (* glGetUniformfv)(GLuint program, GLint location, GLfloat *params);
void (* glGetUniformiv)(GLuint program, GLint location, GLint *params);
void (* glGetVertexAttribdv)(GLuint index, GLenum pname, GLdouble *params);
void (* glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat *params);
void (* glGetVertexAttribiv)(GLuint index, GLenum pname, GLint *params);
void (* glGetVertexAttribPointerv)(GLuint index, GLenum pname, void **pointer);
GLboolean (* glIsProgram)(GLuint program);
GLboolean (* glIsShader)(GLuint shader);
void (* glLinkProgram)(GLuint program);
void (* glShaderSource)(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void (* glUseProgram)(GLuint program);
void (* glUniform1f)(GLint location, GLfloat v0);
void (* glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
void (* glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (* glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (* glUniform1i)(GLint location, GLint v0);
void (* glUniform2i)(GLint location, GLint v0, GLint v1);
void (* glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
void (* glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (* glUniform1fv)(GLint location, GLsizei count, const GLfloat *value);
void (* glUniform2fv)(GLint location, GLsizei count, const GLfloat *value);
void (* glUniform3fv)(GLint location, GLsizei count, const GLfloat *value);
void (* glUniform4fv)(GLint location, GLsizei count, const GLfloat *value);
void (* glUniform1iv)(GLint location, GLsizei count, const GLint *value);
void (* glUniform2iv)(GLint location, GLsizei count, const GLint *value);
void (* glUniform3iv)(GLint location, GLsizei count, const GLint *value);
void (* glUniform4iv)(GLint location, GLsizei count, const GLint *value);
void (* glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glValidateProgram)(GLuint program);
void (* glVertexAttrib1d)(GLuint index, GLdouble x);
void (* glVertexAttrib1dv)(GLuint index, const GLdouble *v);
void (* glVertexAttrib1f)(GLuint index, GLfloat x);
void (* glVertexAttrib1fv)(GLuint index, const GLfloat *v);
void (* glVertexAttrib1s)(GLuint index, GLshort x);
void (* glVertexAttrib1sv)(GLuint index, const GLshort *v);
void (* glVertexAttrib2d)(GLuint index, GLdouble x, GLdouble y);
void (* glVertexAttrib2dv)(GLuint index, const GLdouble *v);
void (* glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
void (* glVertexAttrib2fv)(GLuint index, const GLfloat *v);
void (* glVertexAttrib2s)(GLuint index, GLshort x, GLshort y);
void (* glVertexAttrib2sv)(GLuint index, const GLshort *v);
void (* glVertexAttrib3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
void (* glVertexAttrib3dv)(GLuint index, const GLdouble *v);
void (* glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
void (* glVertexAttrib3fv)(GLuint index, const GLfloat *v);
void (* glVertexAttrib3s)(GLuint index, GLshort x, GLshort y, GLshort z);
void (* glVertexAttrib3sv)(GLuint index, const GLshort *v);
void (* glVertexAttrib4Nbv)(GLuint index, const GLbyte *v);
void (* glVertexAttrib4Niv)(GLuint index, const GLint *v);
void (* glVertexAttrib4Nsv)(GLuint index, const GLshort *v);
void (* glVertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
void (* glVertexAttrib4Nubv)(GLuint index, const GLubyte *v);
void (* glVertexAttrib4Nuiv)(GLuint index, const GLuint *v);
void (* glVertexAttrib4Nusv)(GLuint index, const GLushort *v);
void (* glVertexAttrib4bv)(GLuint index, const GLbyte *v);
void (* glVertexAttrib4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (* glVertexAttrib4dv)(GLuint index, const GLdouble *v);
void (* glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void (* glVertexAttrib4fv)(GLuint index, const GLfloat *v);
void (* glVertexAttrib4iv)(GLuint index, const GLint *v);
void (* glVertexAttrib4s)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
void (* glVertexAttrib4sv)(GLuint index, const GLshort *v);
void (* glVertexAttrib4ubv)(GLuint index, const GLubyte *v);
void (* glVertexAttrib4uiv)(GLuint index, const GLuint *v);
void (* glVertexAttrib4usv)(GLuint index, const GLushort *v);
void (* glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void (* glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glColorMaski)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
void (* glGetBooleani_v)(GLenum target, GLuint index, GLboolean *data);
void (* glGetIntegeri_v)(GLenum target, GLuint index, GLint *data);
void (* glEnablei)(GLenum target, GLuint index);
void (* glDisablei)(GLenum target, GLuint index);
GLboolean (* glIsEnabledi)(GLenum target, GLuint index);
void (* glBeginTransformFeedback)(GLenum primitiveMode);
void (* glEndTransformFeedback)(void);
void (* glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (* glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
void (* glTransformFeedbackVaryings)(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
void (* glGetTransformFeedbackVarying)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
void (* glClampColor)(GLenum target, GLenum clamp);
void (* glBeginConditionalRender)(GLuint id, GLenum mode);
void (* glEndConditionalRender)(void);
void (* glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void (* glGetVertexAttribIiv)(GLuint index, GLenum pname, GLint *params);
void (* glGetVertexAttribIuiv)(GLuint index, GLenum pname, GLuint *params);
void (* glVertexAttribI1i)(GLuint index, GLint x);
void (* glVertexAttribI2i)(GLuint index, GLint x, GLint y);
void (* glVertexAttribI3i)(GLuint index, GLint x, GLint y, GLint z);
void (* glVertexAttribI4i)(GLuint index, GLint x, GLint y, GLint z, GLint w);
void (* glVertexAttribI1ui)(GLuint index, GLuint x);
void (* glVertexAttribI2ui)(GLuint index, GLuint x, GLuint y);
void (* glVertexAttribI3ui)(GLuint index, GLuint x, GLuint y, GLuint z);
void (* glVertexAttribI4ui)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void (* glVertexAttribI1iv)(GLuint index, const GLint *v);
void (* glVertexAttribI2iv)(GLuint index, const GLint *v);
void (* glVertexAttribI3iv)(GLuint index, const GLint *v);
void (* glVertexAttribI4iv)(GLuint index, const GLint *v);
void (* glVertexAttribI1uiv)(GLuint index, const GLuint *v);
void (* glVertexAttribI2uiv)(GLuint index, const GLuint *v);
void (* glVertexAttribI3uiv)(GLuint index, const GLuint *v);
void (* glVertexAttribI4uiv)(GLuint index, const GLuint *v);
void (* glVertexAttribI4bv)(GLuint index, const GLbyte *v);
void (* glVertexAttribI4sv)(GLuint index, const GLshort *v);
void (* glVertexAttribI4ubv)(GLuint index, const GLubyte *v);
void (* glVertexAttribI4usv)(GLuint index, const GLushort *v);
void (* glGetUniformuiv)(GLuint program, GLint location, GLuint *params);
void (* glBindFragDataLocation)(GLuint program, GLuint color, const GLchar *name);
GLint (* glGetFragDataLocation)(GLuint program, const GLchar *name);
void (* glUniform1ui)(GLint location, GLuint v0);
void (* glUniform2ui)(GLint location, GLuint v0, GLuint v1);
void (* glUniform3ui)(GLint location, GLuint v0, GLuint v1, GLuint v2);
void (* glUniform4ui)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void (* glUniform1uiv)(GLint location, GLsizei count, const GLuint *value);
void (* glUniform2uiv)(GLint location, GLsizei count, const GLuint *value);
void (* glUniform3uiv)(GLint location, GLsizei count, const GLuint *value);
void (* glUniform4uiv)(GLint location, GLsizei count, const GLuint *value);
void (* glTexParameterIiv)(GLenum target, GLenum pname, const GLint *params);
void (* glTexParameterIuiv)(GLenum target, GLenum pname, const GLuint *params);
void (* glGetTexParameterIiv)(GLenum target, GLenum pname, GLint *params);
void (* glGetTexParameterIuiv)(GLenum target, GLenum pname, GLuint *params);
void (* glClearBufferiv)(GLenum buffer, GLint drawbuffer, const GLint *value);
void (* glClearBufferuiv)(GLenum buffer, GLint drawbuffer, const GLuint *value);
void (* glClearBufferfv)(GLenum buffer, GLint drawbuffer, const GLfloat *value);
void (* glClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
GLboolean (* glIsRenderbuffer)(GLuint renderbuffer);
void (* glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
void (* glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
void (* glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (* glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void (* glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint *params);
GLboolean (* glIsFramebuffer)(GLuint framebuffer);
void (* glBindFramebuffer)(GLenum target, GLuint framebuffer);
void (* glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
void (* glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
GLenum (* glCheckFramebufferStatus)(GLenum target);
void (* glFramebufferTexture1D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (* glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (* glFramebufferTexture3D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
void (* glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (* glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
void (* glGenerateMipmap)(GLenum target);
void (* glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void (* glRenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void (* glFramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void (* glFlushMappedBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length);
void (* glBindVertexArray)(GLuint array);
void (* glDeleteVertexArrays)(GLsizei n, const GLuint *arrays);
void (* glGenVertexArrays)(GLsizei n, GLuint *arrays);
GLboolean (* glIsVertexArray)(GLuint array);
void (* glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
void (* glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
void (* glTexBuffer)(GLenum target, GLenum internalformat, GLuint buffer);
void (* glPrimitiveRestartIndex)(GLuint index);
void (* glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void (* glGetUniformIndices)(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
void (* glGetActiveUniformsiv)(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
void (* glGetActiveUniformName)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
GLuint (* glGetUniformBlockIndex)(GLuint program, const GLchar *uniformBlockName);
void (* glGetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
void (* glGetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
void (* glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void (* glDrawElementsBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void (* glDrawRangeElementsBaseVertex)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void (* glDrawElementsInstancedBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
void (* glMultiDrawElementsBaseVertex)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex);
void (* glProvokingVertex)(GLenum mode);
GLsync (* glFenceSync)(GLenum condition, GLbitfield flags);
GLboolean (* glIsSync)(GLsync sync);
void (* glDeleteSync)(GLsync sync);
GLenum (* glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (* glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (* glGetInteger64v)(GLenum pname, GLint64 *data);
void (* glGetSynciv)(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
void (* glGetInteger64i_v)(GLenum target, GLuint index, GLint64 *data);
void (* glGetBufferParameteri64v)(GLenum target, GLenum pname, GLint64 *params);
void (* glFramebufferTexture)(GLenum target, GLenum attachment, GLuint texture, GLint level);
void (* glTexImage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (* glTexImage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (* glGetMultisamplefv)(GLenum pname, GLuint index, GLfloat *val);
void (* glSampleMaski)(GLuint maskNumber, GLbitfield mask);
void (* glBindFragDataLocationIndexed)(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name);
GLint (* glGetFragDataIndex)(GLuint program, const GLchar *name);
void (* glGenSamplers)(GLsizei count, GLuint *samplers);
void (* glDeleteSamplers)(GLsizei count, const GLuint *samplers);
GLboolean (* glIsSampler)(GLuint sampler);
void (* glBindSampler)(GLuint unit, GLuint sampler);
void (* glSamplerParameteri)(GLuint sampler, GLenum pname, GLint param);
void (* glSamplerParameteriv)(GLuint sampler, GLenum pname, const GLint *param);
void (* glSamplerParameterf)(GLuint sampler, GLenum pname, GLfloat param);
void (* glSamplerParameterfv)(GLuint sampler, GLenum pname, const GLfloat *param);
void (* glSamplerParameterIiv)(GLuint sampler, GLenum pname, const GLint *param);
void (* glSamplerParameterIuiv)(GLuint sampler, GLenum pname, const GLuint *param);
void (* glGetSamplerParameteriv)(GLuint sampler, GLenum pname, GLint *params);
void (* glGetSamplerParameterIiv)(GLuint sampler, GLenum pname, GLint *params);
void (* glGetSamplerParameterfv)(GLuint sampler, GLenum pname, GLfloat *params);
void (* glGetSamplerParameterIuiv)(GLuint sampler, GLenum pname, GLuint *params);
void (* glQueryCounter)(GLuint id, GLenum target);
void (* glGetQueryObjecti64v)(GLuint id, GLenum pname, GLint64 *params);
void (* glGetQueryObjectui64v)(GLuint id, GLenum pname, GLuint64 *params);
void (* glVertexAttribDivisor)(GLuint index, GLuint divisor);
void (* glVertexAttribP1ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (* glVertexAttribP1uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (* glVertexAttribP2ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (* glVertexAttribP2uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (* glVertexAttribP3ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (* glVertexAttribP3uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (* glVertexAttribP4ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (* glVertexAttribP4uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (* glMinSampleShading)(GLfloat value);
void (* glBlendEquationi)(GLuint buf, GLenum mode);
void (* glBlendEquationSeparatei)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
void (* glBlendFunci)(GLuint buf, GLenum src, GLenum dst);
void (* glBlendFuncSeparatei)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void (* glDrawArraysIndirect)(GLenum mode, const void *indirect);
void (* glDrawElementsIndirect)(GLenum mode, GLenum type, const void *indirect);
void (* glUniform1d)(GLint location, GLdouble x);
void (* glUniform2d)(GLint location, GLdouble x, GLdouble y);
void (* glUniform3d)(GLint location, GLdouble x, GLdouble y, GLdouble z);
void (* glUniform4d)(GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (* glUniform1dv)(GLint location, GLsizei count, const GLdouble *value);
void (* glUniform2dv)(GLint location, GLsizei count, const GLdouble *value);
void (* glUniform3dv)(GLint location, GLsizei count, const GLdouble *value);
void (* glUniform4dv)(GLint location, GLsizei count, const GLdouble *value);
void (* glUniformMatrix2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix2x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix2x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix3x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix3x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix4x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glUniformMatrix4x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glGetUniformdv)(GLuint program, GLint location, GLdouble *params);
GLint (* glGetSubroutineUniformLocation)(GLuint program, GLenum shadertype, const GLchar *name);
GLuint (* glGetSubroutineIndex)(GLuint program, GLenum shadertype, const GLchar *name);
void (* glGetActiveSubroutineUniformiv)(GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values);
void (* glGetActiveSubroutineUniformName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
void (* glGetActiveSubroutineName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
void (* glUniformSubroutinesuiv)(GLenum shadertype, GLsizei count, const GLuint *indices);
void (* glGetUniformSubroutineuiv)(GLenum shadertype, GLint location, GLuint *params);
void (* glGetProgramStageiv)(GLuint program, GLenum shadertype, GLenum pname, GLint *values);
void (* glPatchParameteri)(GLenum pname, GLint value);
void (* glPatchParameterfv)(GLenum pname, const GLfloat *values);
void (* glBindTransformFeedback)(GLenum target, GLuint id);
void (* glDeleteTransformFeedbacks)(GLsizei n, const GLuint *ids);
void (* glGenTransformFeedbacks)(GLsizei n, GLuint *ids);
GLboolean (* glIsTransformFeedback)(GLuint id);
void (* glPauseTransformFeedback)(void);
void (* glResumeTransformFeedback)(void);
void (* glDrawTransformFeedback)(GLenum mode, GLuint id);
void (* glDrawTransformFeedbackStream)(GLenum mode, GLuint id, GLuint stream);
void (* glBeginQueryIndexed)(GLenum target, GLuint index, GLuint id);
void (* glEndQueryIndexed)(GLenum target, GLuint index);
void (* glGetQueryIndexediv)(GLenum target, GLuint index, GLenum pname, GLint *params);
void (* glReleaseShaderCompiler)(void);
void (* glShaderBinary)(GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length);
void (* glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
void (* glDepthRangef)(GLfloat n, GLfloat f);
void (* glClearDepthf)(GLfloat d);
void (* glGetProgramBinary)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
void (* glProgramBinary)(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
void (* glProgramParameteri)(GLuint program, GLenum pname, GLint value);
void (* glUseProgramStages)(GLuint pipeline, GLbitfield stages, GLuint program);
void (* glActiveShaderProgram)(GLuint pipeline, GLuint program);
GLuint (* glCreateShaderProgramv)(GLenum type, GLsizei count, const GLchar *const*strings);
void (* glBindProgramPipeline)(GLuint pipeline);
void (* glDeleteProgramPipelines)(GLsizei n, const GLuint *pipelines);
void (* glGenProgramPipelines)(GLsizei n, GLuint *pipelines);
GLboolean (* glIsProgramPipeline)(GLuint pipeline);
void (* glGetProgramPipelineiv)(GLuint pipeline, GLenum pname, GLint *params);
void (* glProgramUniform1i)(GLuint program, GLint location, GLint v0);
void (* glProgramUniform1iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (* glProgramUniform1f)(GLuint program, GLint location, GLfloat v0);
void (* glProgramUniform1fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (* glProgramUniform1d)(GLuint program, GLint location, GLdouble v0);
void (* glProgramUniform1dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (* glProgramUniform1ui)(GLuint program, GLint location, GLuint v0);
void (* glProgramUniform1uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (* glProgramUniform2i)(GLuint program, GLint location, GLint v0, GLint v1);
void (* glProgramUniform2iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (* glProgramUniform2f)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
void (* glProgramUniform2fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (* glProgramUniform2d)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
void (* glProgramUniform2dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (* glProgramUniform2ui)(GLuint program, GLint location, GLuint v0, GLuint v1);
void (* glProgramUniform2uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (* glProgramUniform3i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
void (* glProgramUniform3iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (* glProgramUniform3f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (* glProgramUniform3fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (* glProgramUniform3d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
void (* glProgramUniform3dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (* glProgramUniform3ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
void (* glProgramUniform3uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (* glProgramUniform4i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (* glProgramUniform4iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (* glProgramUniform4f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (* glProgramUniform4fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (* glProgramUniform4d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
void (* glProgramUniform4dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (* glProgramUniform4ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void (* glProgramUniform4uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (* glProgramUniformMatrix2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix2x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix3x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix2x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix4x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix3x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix4x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (* glProgramUniformMatrix2x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix3x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix2x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix4x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix3x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glProgramUniformMatrix4x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (* glValidateProgramPipeline)(GLuint pipeline);
void (* glGetProgramPipelineInfoLog)(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (* glVertexAttribL1d)(GLuint index, GLdouble x);
void (* glVertexAttribL2d)(GLuint index, GLdouble x, GLdouble y);
void (* glVertexAttribL3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
void (* glVertexAttribL4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (* glVertexAttribL1dv)(GLuint index, const GLdouble *v);
void (* glVertexAttribL2dv)(GLuint index, const GLdouble *v);
void (* glVertexAttribL3dv)(GLuint index, const GLdouble *v);
void (* glVertexAttribL4dv)(GLuint index, const GLdouble *v);
void (* glVertexAttribLPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void (* glGetVertexAttribLdv)(GLuint index, GLenum pname, GLdouble *params);
void (* glViewportArrayv)(GLuint first, GLsizei count, const GLfloat *v);
void (* glViewportIndexedf)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
void (* glViewportIndexedfv)(GLuint index, const GLfloat *v);
void (* glScissorArrayv)(GLuint first, GLsizei count, const GLint *v);
void (* glScissorIndexed)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
void (* glScissorIndexedv)(GLuint index, const GLint *v);
void (* glDepthRangeArrayv)(GLuint first, GLsizei count, const GLdouble *v);
void (* glDepthRangeIndexed)(GLuint index, GLdouble n, GLdouble f);
void (* glGetFloati_v)(GLenum target, GLuint index, GLfloat *data);
void (* glGetDoublei_v)(GLenum target, GLuint index, GLdouble *data);
void (* glDrawArraysInstancedBaseInstance)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
void (* glDrawElementsInstancedBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLuint baseinstance);
void (* glDrawElementsInstancedBaseVertexBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
void (* glGetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
void (* glGetActiveAtomicCounterBufferiv)(GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
void (* glBindImageTexture)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
void (* glMemoryBarrier)(GLbitfield barriers);
void (* glTexStorage1D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
void (* glTexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void (* glTexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void (* glDrawTransformFeedbackInstanced)(GLenum mode, GLuint id, GLsizei instancecount);
void (* glDrawTransformFeedbackStreamInstanced)(GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
void (* glClearBufferData)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
void (* glClearBufferSubData)(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
void (* glDispatchCompute)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
void (* glDispatchComputeIndirect)(GLintptr indirect);
void (* glCopyImageSubData)(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
void (* glFramebufferParameteri)(GLenum target, GLenum pname, GLint param);
void (* glGetFramebufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (* glGetInternalformati64v)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params);
void (* glInvalidateTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
void (* glInvalidateTexImage)(GLuint texture, GLint level);
void (* glInvalidateBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr length);
void (* glInvalidateBufferData)(GLuint buffer);
void (* glInvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum *attachments);
void (* glInvalidateSubFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glMultiDrawArraysIndirect)(GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
void (* glMultiDrawElementsIndirect)(GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
void (* glGetProgramInterfaceiv)(GLuint program, GLenum programInterface, GLenum pname, GLint *params);
GLuint (* glGetProgramResourceIndex)(GLuint program, GLenum programInterface, const GLchar *name);
void (* glGetProgramResourceName)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
void (* glGetProgramResourceiv)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
GLint (* glGetProgramResourceLocation)(GLuint program, GLenum programInterface, const GLchar *name);
GLint (* glGetProgramResourceLocationIndex)(GLuint program, GLenum programInterface, const GLchar *name);
void (* glShaderStorageBlockBinding)(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
void (* glTexBufferRange)(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (* glTexStorage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (* glTexStorage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (* glTextureView)(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
void (* glBindVertexBuffer)(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void (* glVertexAttribFormat)(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void (* glVertexAttribIFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (* glVertexAttribLFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (* glVertexAttribBinding)(GLuint attribindex, GLuint bindingindex);
void (* glVertexBindingDivisor)(GLuint bindingindex, GLuint divisor);
void (* glDebugMessageControl)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
void (* glDebugMessageInsert)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
void (* glDebugMessageCallback)(GLDEBUGPROC callback, const void *userParam);
GLuint (* glGetDebugMessageLog)(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
void (* glPushDebugGroup)(GLenum source, GLuint id, GLsizei length, const GLchar *message);
void (* glPopDebugGroup)(void);
void (* glObjectLabel)(GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
void (* glGetObjectLabel)(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
void (* glObjectPtrLabel)(const void *ptr, GLsizei length, const GLchar *label);
void (* glGetObjectPtrLabel)(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
void (* glBufferStorage)(GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
void (* glClearTexImage)(GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
void (* glClearTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
void (* glBindBuffersBase)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
void (* glBindBuffersRange)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
void (* glBindTextures)(GLuint first, GLsizei count, const GLuint *textures);
void (* glBindSamplers)(GLuint first, GLsizei count, const GLuint *samplers);
void (* glBindImageTextures)(GLuint first, GLsizei count, const GLuint *textures);
void (* glBindVertexBuffers)(GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
void (* glClipControl)(GLenum origin, GLenum depth);
void (* glCreateTransformFeedbacks)(GLsizei n, GLuint *ids);
void (* glTransformFeedbackBufferBase)(GLuint xfb, GLuint index, GLuint buffer);
void (* glTransformFeedbackBufferRange)(GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (* glGetTransformFeedbackiv)(GLuint xfb, GLenum pname, GLint *param);
void (* glGetTransformFeedbacki_v)(GLuint xfb, GLenum pname, GLuint index, GLint *param);
void (* glGetTransformFeedbacki64_v)(GLuint xfb, GLenum pname, GLuint index, GLint64 *param);
void (* glCreateBuffers)(GLsizei n, GLuint *buffers);
void (* glNamedBufferStorage)(GLuint buffer, GLsizeiptr size, const void *data, GLbitfield flags);
void (* glNamedBufferData)(GLuint buffer, GLsizeiptr size, const void *data, GLenum usage);
void (* glNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);
void (* glCopyNamedBufferSubData)(GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void (* glClearNamedBufferData)(GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void *data);
void (* glClearNamedBufferSubData)(GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
GLboolean (* glUnmapNamedBuffer)(GLuint buffer);
void (* glFlushMappedNamedBufferRange)(GLuint buffer, GLintptr offset, GLsizeiptr length);
void (* glGetNamedBufferParameteriv)(GLuint buffer, GLenum pname, GLint *params);
void (* glGetNamedBufferParameteri64v)(GLuint buffer, GLenum pname, GLint64 *params);
void (* glGetNamedBufferPointerv)(GLuint buffer, GLenum pname, void **params);
void (* glGetNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, void *data);
void (* glCreateFramebuffers)(GLsizei n, GLuint *framebuffers);
void (* glNamedFramebufferRenderbuffer)(GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (* glNamedFramebufferParameteri)(GLuint framebuffer, GLenum pname, GLint param);
void (* glNamedFramebufferTexture)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level);
void (* glNamedFramebufferTextureLayer)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer);
void (* glNamedFramebufferDrawBuffer)(GLuint framebuffer, GLenum buf);
void (* glNamedFramebufferDrawBuffers)(GLuint framebuffer, GLsizei n, const GLenum *bufs);
void (* glNamedFramebufferReadBuffer)(GLuint framebuffer, GLenum src);
void (* glInvalidateNamedFramebufferData)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments);
void (* glInvalidateNamedFramebufferSubData)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glClearNamedFramebufferiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint *value);
void (* glClearNamedFramebufferuiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint *value);
void (* glClearNamedFramebufferfv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value);
void (* glClearNamedFramebufferfi)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
void (* glBlitNamedFramebuffer)(GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
GLenum (* glCheckNamedFramebufferStatus)(GLuint framebuffer, GLenum target);
void (* glGetNamedFramebufferParameteriv)(GLuint framebuffer, GLenum pname, GLint *param);
void (* glGetNamedFramebufferAttachmentParameteriv)(GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params);
void (* glCreateRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (* glNamedRenderbufferStorage)(GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height);
void (* glNamedRenderbufferStorageMultisample)(GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void (* glGetNamedRenderbufferParameteriv)(GLuint renderbuffer, GLenum pname, GLint *params);
void (* glCreateTextures)(GLenum target, GLsizei n, GLuint *textures);
void (* glTextureBuffer)(GLuint texture, GLenum internalformat, GLuint buffer);
void (* glTextureBufferRange)(GLuint texture, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (* glTextureStorage1D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width);
void (* glTextureStorage2D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void (* glTextureStorage3D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void (* glTextureStorage2DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (* glTextureStorage3DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (* glTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
void (* glTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void (* glTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void (* glCompressedTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
void (* glCompressedTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void (* glCompressedTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void (* glCopyTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void (* glCopyTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glCopyTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (* glTextureParameterf)(GLuint texture, GLenum pname, GLfloat param);
void (* glTextureParameterfv)(GLuint texture, GLenum pname, const GLfloat *param);
void (* glTextureParameteri)(GLuint texture, GLenum pname, GLint param);
void (* glTextureParameterIiv)(GLuint texture, GLenum pname, const GLint *params);
void (* glTextureParameterIuiv)(GLuint texture, GLenum pname, const GLuint *params);
void (* glTextureParameteriv)(GLuint texture, GLenum pname, const GLint *param);
void (* glGenerateTextureMipmap)(GLuint texture);
void (* glBindTextureUnit)(GLuint unit, GLuint texture);
void (* glGetTextureImage)(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (* glGetCompressedTextureImage)(GLuint texture, GLint level, GLsizei bufSize, void *pixels);
void (* glGetTextureLevelParameterfv)(GLuint texture, GLint level, GLenum pname, GLfloat *params);
void (* glGetTextureLevelParameteriv)(GLuint texture, GLint level, GLenum pname, GLint *params);
void (* glGetTextureParameterfv)(GLuint texture, GLenum pname, GLfloat *params);
void (* glGetTextureParameterIiv)(GLuint texture, GLenum pname, GLint *params);
void (* glGetTextureParameterIuiv)(GLuint texture, GLenum pname, GLuint *params);
void (* glGetTextureParameteriv)(GLuint texture, GLenum pname, GLint *params);
void (* glCreateVertexArrays)(GLsizei n, GLuint *arrays);
void (* glDisableVertexArrayAttrib)(GLuint vaobj, GLuint index);
void (* glEnableVertexArrayAttrib)(GLuint vaobj, GLuint index);
void (* glVertexArrayElementBuffer)(GLuint vaobj, GLuint buffer);
void (* glVertexArrayVertexBuffer)(GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void (* glVertexArrayVertexBuffers)(GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
void (* glVertexArrayAttribBinding)(GLuint vaobj, GLuint attribindex, GLuint bindingindex);
void (* glVertexArrayAttribFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void (* glVertexArrayAttribIFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (* glVertexArrayAttribLFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (* glVertexArrayBindingDivisor)(GLuint vaobj, GLuint bindingindex, GLuint divisor);
void (* glGetVertexArrayiv)(GLuint vaobj, GLenum pname, GLint *param);
void (* glGetVertexArrayIndexediv)(GLuint vaobj, GLuint index, GLenum pname, GLint *param);
void (* glGetVertexArrayIndexed64iv)(GLuint vaobj, GLuint index, GLenum pname, GLint64 *param);
void (* glCreateSamplers)(GLsizei n, GLuint *samplers);
void (* glCreateProgramPipelines)(GLsizei n, GLuint *pipelines);
void (* glCreateQueries)(GLenum target, GLsizei n, GLuint *ids);
void (* glGetQueryBufferObjecti64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (* glGetQueryBufferObjectiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (* glGetQueryBufferObjectui64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (* glGetQueryBufferObjectuiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (* glMemoryBarrierByRegion)(GLbitfield barriers);
void (* glGetTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (* glGetCompressedTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels);
GLenum (* glGetGraphicsResetStatus)(void);
void (* glGetnCompressedTexImage)(GLenum target, GLint lod, GLsizei bufSize, void *pixels);
void (* glGetnTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (* glGetnUniformdv)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
void (* glGetnUniformfv)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
void (* glGetnUniformiv)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
void (* glGetnUniformuiv)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
void (* glReadnPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
void (* glTextureBarrier)(void);
GLuint64 (* glGetTextureHandleARB)(GLuint texture);
GLuint64 (* glGetTextureSamplerHandleARB)(GLuint texture, GLuint sampler);
void (* glMakeTextureHandleResidentARB)(GLuint64 handle);
void (* glMakeTextureHandleNonResidentARB)(GLuint64 handle);
GLuint64 (* glGetImageHandleARB)(GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum format);
void (* glMakeImageHandleResidentARB)(GLuint64 handle, GLenum access);
void (* glMakeImageHandleNonResidentARB)(GLuint64 handle);
void (* glUniformHandleui64ARB)(GLint location, GLuint64 value);
void (* glUniformHandleui64vARB)(GLint location, GLsizei count, const GLuint64 *value);
void (* glProgramUniformHandleui64ARB)(GLuint program, GLint location, GLuint64 value);
void (* glProgramUniformHandleui64vARB)(GLuint program, GLint location, GLsizei count, const GLuint64 *values);
GLboolean (* glIsTextureHandleResidentARB)(GLuint64 handle);
GLboolean (* glIsImageHandleResidentARB)(GLuint64 handle);
void (* glVertexAttribL1ui64ARB)(GLuint index, GLuint64EXT x);
void (* glVertexAttribL1ui64vARB)(GLuint index, const GLuint64EXT *v);
void (* glGetVertexAttribLui64vARB)(GLuint index, GLenum pname, GLuint64EXT *params);
GLsync (* glCreateSyncFromCLeventARB)(struct _cl_context *context, struct _cl_event *event, GLbitfield flags);
void (* glDispatchComputeGroupSizeARB)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z);
void (* glDebugMessageControlARB)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
void (* glDebugMessageInsertARB)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
void (* glDebugMessageCallbackARB)(GLDEBUGPROCARB callback, const void *userParam);
GLuint (* glGetDebugMessageLogARB)(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
void (* glBlendEquationiARB)(GLuint buf, GLenum mode);
void (* glBlendEquationSeparateiARB)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
void (* glBlendFunciARB)(GLuint buf, GLenum src, GLenum dst);
void (* glBlendFuncSeparateiARB)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void (* glMultiDrawArraysIndirectCountARB)(GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
void (* glMultiDrawElementsIndirectCountARB)(GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
GLenum (* glGetGraphicsResetStatusARB)(void);
void (* glGetnTexImageARB)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *img);
void (* glReadnPixelsARB)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
void (* glGetnCompressedTexImageARB)(GLenum target, GLint lod, GLsizei bufSize, void *img);
void (* glGetnUniformfvARB)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
void (* glGetnUniformivARB)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
void (* glGetnUniformuivARB)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
void (* glGetnUniformdvARB)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
void (* glMinSampleShadingARB)(GLfloat value);
void (* glNamedStringARB)(GLenum type, GLint namelen, const GLchar *name, GLint stringlen, const GLchar *string);
void (* glDeleteNamedStringARB)(GLint namelen, const GLchar *name);
void (* glCompileShaderIncludeARB)(GLuint shader, GLsizei count, const GLchar *const*path, const GLint *length);
GLboolean (* glIsNamedStringARB)(GLint namelen, const GLchar *name);
void (* glGetNamedStringARB)(GLint namelen, const GLchar *name, GLsizei bufSize, GLint *stringlen, GLchar *string);
void (* glGetNamedStringivARB)(GLint namelen, const GLchar *name, GLenum pname, GLint *params);
void (* glBufferPageCommitmentARB)(GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (* glNamedBufferPageCommitmentEXT)(GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (* glNamedBufferPageCommitmentARB)(GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (* glTexPageCommitmentARB)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLboolean commit);


//////////////////////////////////
// func is an OpenGL function, e.g: glBindVertexArray
// XOGL_GET_PROC(glBindVertexArray) =>
//     glBindVertexArray = xogl_context_getProc("glBindVertexArray");
//     if (!glBindVertexArray) fprintf(stderr, "Unable to get proc glBindVertexArray\n");
//////////////////////////////////
#define XOGL_GET_PROC(func)\
func = xogl_context_getProc(#func);\
if (!func) fprintf(stderr, "Unable to get proc " #func "\n");\

int xogl_init(Display* disp, Window win, int major, int minor) {
    
    if (xogl_context_create(disp, win, major, minor)) {
        return -1;
    }

    XOGL_GET_PROC(glCullFace);
    XOGL_GET_PROC(glFrontFace);
    XOGL_GET_PROC(glHint);
    XOGL_GET_PROC(glLineWidth);
    XOGL_GET_PROC(glPointSize);
    XOGL_GET_PROC(glPolygonMode);
    XOGL_GET_PROC(glScissor);
    XOGL_GET_PROC(glTexParameterf);
    XOGL_GET_PROC(glTexParameterfv);
    XOGL_GET_PROC(glTexParameteri);
    XOGL_GET_PROC(glTexParameteriv);
    XOGL_GET_PROC(glTexImage1D);
    XOGL_GET_PROC(glTexImage2D);
    XOGL_GET_PROC(glDrawBuffer);
    XOGL_GET_PROC(glClear);
    XOGL_GET_PROC(glClearColor);
    XOGL_GET_PROC(glClearStencil);
    XOGL_GET_PROC(glClearDepth);
    XOGL_GET_PROC(glStencilMask);
    XOGL_GET_PROC(glColorMask);
    XOGL_GET_PROC(glDepthMask);
    XOGL_GET_PROC(glDisable);
    XOGL_GET_PROC(glEnable);
    XOGL_GET_PROC(glFinish);
    XOGL_GET_PROC(glFlush);
    XOGL_GET_PROC(glBlendFunc);
    XOGL_GET_PROC(glLogicOp);
    XOGL_GET_PROC(glStencilFunc);
    XOGL_GET_PROC(glStencilOp);
    XOGL_GET_PROC(glDepthFunc);
    XOGL_GET_PROC(glPixelStoref);
    XOGL_GET_PROC(glPixelStorei);
    XOGL_GET_PROC(glReadBuffer);
    XOGL_GET_PROC(glReadPixels);
    XOGL_GET_PROC(glGetBooleanv);
    XOGL_GET_PROC(glGetDoublev);
    XOGL_GET_PROC(glGetError);
    XOGL_GET_PROC(glGetFloatv);
    XOGL_GET_PROC(glGetIntegerv);
    XOGL_GET_PROC(glGetTexImage);
    XOGL_GET_PROC(glGetTexParameterfv);
    XOGL_GET_PROC(glGetTexParameteriv);
    XOGL_GET_PROC(glGetTexLevelParameterfv);
    XOGL_GET_PROC(glGetTexLevelParameteriv);
    XOGL_GET_PROC(glIsEnabled);
    XOGL_GET_PROC(glDepthRange);
    XOGL_GET_PROC(glViewport);
    XOGL_GET_PROC(glDrawArrays);
    XOGL_GET_PROC(glDrawElements);
    XOGL_GET_PROC(glGetPointerv);
    XOGL_GET_PROC(glPolygonOffset);
    XOGL_GET_PROC(glCopyTexImage1D);
    XOGL_GET_PROC(glCopyTexImage2D);
    XOGL_GET_PROC(glCopyTexSubImage1D);
    XOGL_GET_PROC(glCopyTexSubImage2D);
    XOGL_GET_PROC(glTexSubImage1D);
    XOGL_GET_PROC(glTexSubImage2D);
    XOGL_GET_PROC(glBindTexture);
    XOGL_GET_PROC(glDeleteTextures);
    XOGL_GET_PROC(glGenTextures);
    XOGL_GET_PROC(glIsTexture);
    XOGL_GET_PROC(glDrawRangeElements);
    XOGL_GET_PROC(glTexImage3D);
    XOGL_GET_PROC(glTexSubImage3D);
    XOGL_GET_PROC(glCopyTexSubImage3D);
    XOGL_GET_PROC(glActiveTexture);
    XOGL_GET_PROC(glSampleCoverage);
    XOGL_GET_PROC(glCompressedTexImage3D);
    XOGL_GET_PROC(glCompressedTexImage2D);
    XOGL_GET_PROC(glCompressedTexImage1D);
    XOGL_GET_PROC(glCompressedTexSubImage3D);
    XOGL_GET_PROC(glCompressedTexSubImage2D);
    XOGL_GET_PROC(glCompressedTexSubImage1D);
    XOGL_GET_PROC(glGetCompressedTexImage);
    XOGL_GET_PROC(glBlendFuncSeparate);
    XOGL_GET_PROC(glMultiDrawArrays);
    XOGL_GET_PROC(glMultiDrawElements);
    XOGL_GET_PROC(glPointParameterf);
    XOGL_GET_PROC(glPointParameterfv);
    XOGL_GET_PROC(glPointParameteri);
    XOGL_GET_PROC(glPointParameteriv);
    XOGL_GET_PROC(glBlendColor);
    XOGL_GET_PROC(glBlendEquation);
    XOGL_GET_PROC(glGenQueries);
    XOGL_GET_PROC(glDeleteQueries);
    XOGL_GET_PROC(glIsQuery);
    XOGL_GET_PROC(glBeginQuery);
    XOGL_GET_PROC(glEndQuery);
    XOGL_GET_PROC(glGetQueryiv);
    XOGL_GET_PROC(glGetQueryObjectiv);
    XOGL_GET_PROC(glGetQueryObjectuiv);
    XOGL_GET_PROC(glBindBuffer);
    XOGL_GET_PROC(glDeleteBuffers);
    XOGL_GET_PROC(glGenBuffers);
    XOGL_GET_PROC(glIsBuffer);
    XOGL_GET_PROC(glBufferData);
    XOGL_GET_PROC(glBufferSubData);
    XOGL_GET_PROC(glGetBufferSubData);
    XOGL_GET_PROC(glUnmapBuffer);
    XOGL_GET_PROC(glGetBufferParameteriv);
    XOGL_GET_PROC(glGetBufferPointerv);
    XOGL_GET_PROC(glBlendEquationSeparate);
    XOGL_GET_PROC(glDrawBuffers);
    XOGL_GET_PROC(glStencilOpSeparate);
    XOGL_GET_PROC(glStencilFuncSeparate);
    XOGL_GET_PROC(glStencilMaskSeparate);
    XOGL_GET_PROC(glAttachShader);
    XOGL_GET_PROC(glBindAttribLocation);
    XOGL_GET_PROC(glCompileShader);
    XOGL_GET_PROC(glCreateProgram);
    XOGL_GET_PROC(glCreateShader);
    XOGL_GET_PROC(glDeleteProgram);
    XOGL_GET_PROC(glDeleteShader);
    XOGL_GET_PROC(glDetachShader);
    XOGL_GET_PROC(glDisableVertexAttribArray);
    XOGL_GET_PROC(glEnableVertexAttribArray);
    XOGL_GET_PROC(glGetActiveAttrib);
    XOGL_GET_PROC(glGetActiveUniform);
    XOGL_GET_PROC(glGetAttachedShaders);
    XOGL_GET_PROC(glGetAttribLocation);
    XOGL_GET_PROC(glGetProgramiv);
    XOGL_GET_PROC(glGetProgramInfoLog);
    XOGL_GET_PROC(glGetShaderiv);
    XOGL_GET_PROC(glGetShaderInfoLog);
    XOGL_GET_PROC(glGetShaderSource);
    XOGL_GET_PROC(glGetUniformLocation);
    XOGL_GET_PROC(glGetUniformfv);
    XOGL_GET_PROC(glGetUniformiv);
    XOGL_GET_PROC(glGetVertexAttribdv);
    XOGL_GET_PROC(glGetVertexAttribfv);
    XOGL_GET_PROC(glGetVertexAttribiv);
    XOGL_GET_PROC(glGetVertexAttribPointerv);
    XOGL_GET_PROC(glIsProgram);
    XOGL_GET_PROC(glIsShader);
    XOGL_GET_PROC(glLinkProgram);
    XOGL_GET_PROC(glShaderSource);
    XOGL_GET_PROC(glUseProgram);
    XOGL_GET_PROC(glUniform1f);
    XOGL_GET_PROC(glUniform2f);
    XOGL_GET_PROC(glUniform3f);
    XOGL_GET_PROC(glUniform4f);
    XOGL_GET_PROC(glUniform1i);
    XOGL_GET_PROC(glUniform2i);
    XOGL_GET_PROC(glUniform3i);
    XOGL_GET_PROC(glUniform4i);
    XOGL_GET_PROC(glUniform1fv);
    XOGL_GET_PROC(glUniform2fv);
    XOGL_GET_PROC(glUniform3fv);
    XOGL_GET_PROC(glUniform4fv);
    XOGL_GET_PROC(glUniform1iv);
    XOGL_GET_PROC(glUniform2iv);
    XOGL_GET_PROC(glUniform3iv);
    XOGL_GET_PROC(glUniform4iv);
    XOGL_GET_PROC(glUniformMatrix2fv);
    XOGL_GET_PROC(glUniformMatrix3fv);
    XOGL_GET_PROC(glUniformMatrix4fv);
    XOGL_GET_PROC(glValidateProgram);
    XOGL_GET_PROC(glVertexAttrib1d);
    XOGL_GET_PROC(glVertexAttrib1dv);
    XOGL_GET_PROC(glVertexAttrib1f);
    XOGL_GET_PROC(glVertexAttrib1fv);
    XOGL_GET_PROC(glVertexAttrib1s);
    XOGL_GET_PROC(glVertexAttrib1sv);
    XOGL_GET_PROC(glVertexAttrib2d);
    XOGL_GET_PROC(glVertexAttrib2dv);
    XOGL_GET_PROC(glVertexAttrib2f);
    XOGL_GET_PROC(glVertexAttrib2fv);
    XOGL_GET_PROC(glVertexAttrib2s);
    XOGL_GET_PROC(glVertexAttrib2sv);
    XOGL_GET_PROC(glVertexAttrib3d);
    XOGL_GET_PROC(glVertexAttrib3dv);
    XOGL_GET_PROC(glVertexAttrib3f);
    XOGL_GET_PROC(glVertexAttrib3fv);
    XOGL_GET_PROC(glVertexAttrib3s);
    XOGL_GET_PROC(glVertexAttrib3sv);
    XOGL_GET_PROC(glVertexAttrib4Nbv);
    XOGL_GET_PROC(glVertexAttrib4Niv);
    XOGL_GET_PROC(glVertexAttrib4Nsv);
    XOGL_GET_PROC(glVertexAttrib4Nub);
    XOGL_GET_PROC(glVertexAttrib4Nubv);
    XOGL_GET_PROC(glVertexAttrib4Nuiv);
    XOGL_GET_PROC(glVertexAttrib4Nusv);
    XOGL_GET_PROC(glVertexAttrib4bv);
    XOGL_GET_PROC(glVertexAttrib4d);
    XOGL_GET_PROC(glVertexAttrib4dv);
    XOGL_GET_PROC(glVertexAttrib4f);
    XOGL_GET_PROC(glVertexAttrib4fv);
    XOGL_GET_PROC(glVertexAttrib4iv);
    XOGL_GET_PROC(glVertexAttrib4s);
    XOGL_GET_PROC(glVertexAttrib4sv);
    XOGL_GET_PROC(glVertexAttrib4ubv);
    XOGL_GET_PROC(glVertexAttrib4uiv);
    XOGL_GET_PROC(glVertexAttrib4usv);
    XOGL_GET_PROC(glVertexAttribPointer);
    XOGL_GET_PROC(glUniformMatrix2x3fv);
    XOGL_GET_PROC(glUniformMatrix3x2fv);
    XOGL_GET_PROC(glUniformMatrix2x4fv);
    XOGL_GET_PROC(glUniformMatrix4x2fv);
    XOGL_GET_PROC(glUniformMatrix3x4fv);
    XOGL_GET_PROC(glUniformMatrix4x3fv);
    XOGL_GET_PROC(glColorMaski);
    XOGL_GET_PROC(glGetBooleani_v);
    XOGL_GET_PROC(glGetIntegeri_v);
    XOGL_GET_PROC(glEnablei);
    XOGL_GET_PROC(glDisablei);
    XOGL_GET_PROC(glIsEnabledi);
    XOGL_GET_PROC(glBeginTransformFeedback);
    XOGL_GET_PROC(glEndTransformFeedback);
    XOGL_GET_PROC(glBindBufferRange);
    XOGL_GET_PROC(glBindBufferBase);
    XOGL_GET_PROC(glTransformFeedbackVaryings);
    XOGL_GET_PROC(glGetTransformFeedbackVarying);
    XOGL_GET_PROC(glClampColor);
    XOGL_GET_PROC(glBeginConditionalRender);
    XOGL_GET_PROC(glEndConditionalRender);
    XOGL_GET_PROC(glVertexAttribIPointer);
    XOGL_GET_PROC(glGetVertexAttribIiv);
    XOGL_GET_PROC(glGetVertexAttribIuiv);
    XOGL_GET_PROC(glVertexAttribI1i);
    XOGL_GET_PROC(glVertexAttribI2i);
    XOGL_GET_PROC(glVertexAttribI3i);
    XOGL_GET_PROC(glVertexAttribI4i);
    XOGL_GET_PROC(glVertexAttribI1ui);
    XOGL_GET_PROC(glVertexAttribI2ui);
    XOGL_GET_PROC(glVertexAttribI3ui);
    XOGL_GET_PROC(glVertexAttribI4ui);
    XOGL_GET_PROC(glVertexAttribI1iv);
    XOGL_GET_PROC(glVertexAttribI2iv);
    XOGL_GET_PROC(glVertexAttribI3iv);
    XOGL_GET_PROC(glVertexAttribI4iv);
    XOGL_GET_PROC(glVertexAttribI1uiv);
    XOGL_GET_PROC(glVertexAttribI2uiv);
    XOGL_GET_PROC(glVertexAttribI3uiv);
    XOGL_GET_PROC(glVertexAttribI4uiv);
    XOGL_GET_PROC(glVertexAttribI4bv);
    XOGL_GET_PROC(glVertexAttribI4sv);
    XOGL_GET_PROC(glVertexAttribI4ubv);
    XOGL_GET_PROC(glVertexAttribI4usv);
    XOGL_GET_PROC(glGetUniformuiv);
    XOGL_GET_PROC(glBindFragDataLocation);
    XOGL_GET_PROC(glGetFragDataLocation);
    XOGL_GET_PROC(glUniform1ui);
    XOGL_GET_PROC(glUniform2ui);
    XOGL_GET_PROC(glUniform3ui);
    XOGL_GET_PROC(glUniform4ui);
    XOGL_GET_PROC(glUniform1uiv);
    XOGL_GET_PROC(glUniform2uiv);
    XOGL_GET_PROC(glUniform3uiv);
    XOGL_GET_PROC(glUniform4uiv);
    XOGL_GET_PROC(glTexParameterIiv);
    XOGL_GET_PROC(glTexParameterIuiv);
    XOGL_GET_PROC(glGetTexParameterIiv);
    XOGL_GET_PROC(glGetTexParameterIuiv);
    XOGL_GET_PROC(glClearBufferiv);
    XOGL_GET_PROC(glClearBufferuiv);
    XOGL_GET_PROC(glClearBufferfv);
    XOGL_GET_PROC(glClearBufferfi);
    XOGL_GET_PROC(glIsRenderbuffer);
    XOGL_GET_PROC(glBindRenderbuffer);
    XOGL_GET_PROC(glDeleteRenderbuffers);
    XOGL_GET_PROC(glGenRenderbuffers);
    XOGL_GET_PROC(glRenderbufferStorage);
    XOGL_GET_PROC(glGetRenderbufferParameteriv);
    XOGL_GET_PROC(glIsFramebuffer);
    XOGL_GET_PROC(glBindFramebuffer);
    XOGL_GET_PROC(glDeleteFramebuffers);
    XOGL_GET_PROC(glGenFramebuffers);
    XOGL_GET_PROC(glCheckFramebufferStatus);
    XOGL_GET_PROC(glFramebufferTexture1D);
    XOGL_GET_PROC(glFramebufferTexture2D);
    XOGL_GET_PROC(glFramebufferTexture3D);
    XOGL_GET_PROC(glFramebufferRenderbuffer);
    XOGL_GET_PROC(glGetFramebufferAttachmentParameteriv);
    XOGL_GET_PROC(glGenerateMipmap);
    XOGL_GET_PROC(glBlitFramebuffer);
    XOGL_GET_PROC(glRenderbufferStorageMultisample);
    XOGL_GET_PROC(glFramebufferTextureLayer);
    XOGL_GET_PROC(glFlushMappedBufferRange);
    XOGL_GET_PROC(glBindVertexArray);
    XOGL_GET_PROC(glDeleteVertexArrays);
    XOGL_GET_PROC(glGenVertexArrays);
    XOGL_GET_PROC(glIsVertexArray);
    XOGL_GET_PROC(glDrawArraysInstanced);
    XOGL_GET_PROC(glDrawElementsInstanced);
    XOGL_GET_PROC(glTexBuffer);
    XOGL_GET_PROC(glPrimitiveRestartIndex);
    XOGL_GET_PROC(glCopyBufferSubData);
    XOGL_GET_PROC(glGetUniformIndices);
    XOGL_GET_PROC(glGetActiveUniformsiv);
    XOGL_GET_PROC(glGetActiveUniformName);
    XOGL_GET_PROC(glGetUniformBlockIndex);
    XOGL_GET_PROC(glGetActiveUniformBlockiv);
    XOGL_GET_PROC(glGetActiveUniformBlockName);
    XOGL_GET_PROC(glUniformBlockBinding);
    XOGL_GET_PROC(glDrawElementsBaseVertex);
    XOGL_GET_PROC(glDrawRangeElementsBaseVertex);
    XOGL_GET_PROC(glDrawElementsInstancedBaseVertex);
    XOGL_GET_PROC(glMultiDrawElementsBaseVertex);
    XOGL_GET_PROC(glProvokingVertex);
    XOGL_GET_PROC(glFenceSync);
    XOGL_GET_PROC(glIsSync);
    XOGL_GET_PROC(glDeleteSync);
    XOGL_GET_PROC(glClientWaitSync);
    XOGL_GET_PROC(glWaitSync);
    XOGL_GET_PROC(glGetInteger64v);
    XOGL_GET_PROC(glGetSynciv);
    XOGL_GET_PROC(glGetInteger64i_v);
    XOGL_GET_PROC(glGetBufferParameteri64v);
    XOGL_GET_PROC(glFramebufferTexture);
    XOGL_GET_PROC(glTexImage2DMultisample);
    XOGL_GET_PROC(glTexImage3DMultisample);
    XOGL_GET_PROC(glGetMultisamplefv);
    XOGL_GET_PROC(glSampleMaski);
    XOGL_GET_PROC(glBindFragDataLocationIndexed);
    XOGL_GET_PROC(glGetFragDataIndex);
    XOGL_GET_PROC(glGenSamplers);
    XOGL_GET_PROC(glDeleteSamplers);
    XOGL_GET_PROC(glIsSampler);
    XOGL_GET_PROC(glBindSampler);
    XOGL_GET_PROC(glSamplerParameteri);
    XOGL_GET_PROC(glSamplerParameteriv);
    XOGL_GET_PROC(glSamplerParameterf);
    XOGL_GET_PROC(glSamplerParameterfv);
    XOGL_GET_PROC(glSamplerParameterIiv);
    XOGL_GET_PROC(glSamplerParameterIuiv);
    XOGL_GET_PROC(glGetSamplerParameteriv);
    XOGL_GET_PROC(glGetSamplerParameterIiv);
    XOGL_GET_PROC(glGetSamplerParameterfv);
    XOGL_GET_PROC(glGetSamplerParameterIuiv);
    XOGL_GET_PROC(glQueryCounter);
    XOGL_GET_PROC(glGetQueryObjecti64v);
    XOGL_GET_PROC(glGetQueryObjectui64v);
    XOGL_GET_PROC(glVertexAttribDivisor);
    XOGL_GET_PROC(glVertexAttribP1ui);
    XOGL_GET_PROC(glVertexAttribP1uiv);
    XOGL_GET_PROC(glVertexAttribP2ui);
    XOGL_GET_PROC(glVertexAttribP2uiv);
    XOGL_GET_PROC(glVertexAttribP3ui);
    XOGL_GET_PROC(glVertexAttribP3uiv);
    XOGL_GET_PROC(glVertexAttribP4ui);
    XOGL_GET_PROC(glVertexAttribP4uiv);
    XOGL_GET_PROC(glMinSampleShading);
    XOGL_GET_PROC(glBlendEquationi);
    XOGL_GET_PROC(glBlendEquationSeparatei);
    XOGL_GET_PROC(glBlendFunci);
    XOGL_GET_PROC(glBlendFuncSeparatei);
    XOGL_GET_PROC(glDrawArraysIndirect);
    XOGL_GET_PROC(glDrawElementsIndirect);
    XOGL_GET_PROC(glUniform1d);
    XOGL_GET_PROC(glUniform2d);
    XOGL_GET_PROC(glUniform3d);
    XOGL_GET_PROC(glUniform4d);
    XOGL_GET_PROC(glUniform1dv);
    XOGL_GET_PROC(glUniform2dv);
    XOGL_GET_PROC(glUniform3dv);
    XOGL_GET_PROC(glUniform4dv);
    XOGL_GET_PROC(glUniformMatrix2dv);
    XOGL_GET_PROC(glUniformMatrix3dv);
    XOGL_GET_PROC(glUniformMatrix4dv);
    XOGL_GET_PROC(glUniformMatrix2x3dv);
    XOGL_GET_PROC(glUniformMatrix2x4dv);
    XOGL_GET_PROC(glUniformMatrix3x2dv);
    XOGL_GET_PROC(glUniformMatrix3x4dv);
    XOGL_GET_PROC(glUniformMatrix4x2dv);
    XOGL_GET_PROC(glUniformMatrix4x3dv);
    XOGL_GET_PROC(glGetUniformdv);
    XOGL_GET_PROC(glGetSubroutineUniformLocation);
    XOGL_GET_PROC(glGetSubroutineIndex);
    XOGL_GET_PROC(glGetActiveSubroutineUniformiv);
    XOGL_GET_PROC(glGetActiveSubroutineUniformName);
    XOGL_GET_PROC(glGetActiveSubroutineName);
    XOGL_GET_PROC(glUniformSubroutinesuiv);
    XOGL_GET_PROC(glGetUniformSubroutineuiv);
    XOGL_GET_PROC(glGetProgramStageiv);
    XOGL_GET_PROC(glPatchParameteri);
    XOGL_GET_PROC(glPatchParameterfv);
    XOGL_GET_PROC(glBindTransformFeedback);
    XOGL_GET_PROC(glDeleteTransformFeedbacks);
    XOGL_GET_PROC(glGenTransformFeedbacks);
    XOGL_GET_PROC(glIsTransformFeedback);
    XOGL_GET_PROC(glPauseTransformFeedback);
    XOGL_GET_PROC(glResumeTransformFeedback);
    XOGL_GET_PROC(glDrawTransformFeedback);
    XOGL_GET_PROC(glDrawTransformFeedbackStream);
    XOGL_GET_PROC(glBeginQueryIndexed);
    XOGL_GET_PROC(glEndQueryIndexed);
    XOGL_GET_PROC(glGetQueryIndexediv);
    XOGL_GET_PROC(glReleaseShaderCompiler);
    XOGL_GET_PROC(glShaderBinary);
    XOGL_GET_PROC(glGetShaderPrecisionFormat);
    XOGL_GET_PROC(glDepthRangef);
    XOGL_GET_PROC(glClearDepthf);
    XOGL_GET_PROC(glGetProgramBinary);
    XOGL_GET_PROC(glProgramBinary);
    XOGL_GET_PROC(glProgramParameteri);
    XOGL_GET_PROC(glUseProgramStages);
    XOGL_GET_PROC(glActiveShaderProgram);
    XOGL_GET_PROC(glCreateShaderProgramv);
    XOGL_GET_PROC(glBindProgramPipeline);
    XOGL_GET_PROC(glDeleteProgramPipelines);
    XOGL_GET_PROC(glGenProgramPipelines);
    XOGL_GET_PROC(glIsProgramPipeline);
    XOGL_GET_PROC(glGetProgramPipelineiv);
    XOGL_GET_PROC(glProgramUniform1i);
    XOGL_GET_PROC(glProgramUniform1iv);
    XOGL_GET_PROC(glProgramUniform1f);
    XOGL_GET_PROC(glProgramUniform1fv);
    XOGL_GET_PROC(glProgramUniform1d);
    XOGL_GET_PROC(glProgramUniform1dv);
    XOGL_GET_PROC(glProgramUniform1ui);
    XOGL_GET_PROC(glProgramUniform1uiv);
    XOGL_GET_PROC(glProgramUniform2i);
    XOGL_GET_PROC(glProgramUniform2iv);
    XOGL_GET_PROC(glProgramUniform2f);
    XOGL_GET_PROC(glProgramUniform2fv);
    XOGL_GET_PROC(glProgramUniform2d);
    XOGL_GET_PROC(glProgramUniform2dv);
    XOGL_GET_PROC(glProgramUniform2ui);
    XOGL_GET_PROC(glProgramUniform2uiv);
    XOGL_GET_PROC(glProgramUniform3i);
    XOGL_GET_PROC(glProgramUniform3iv);
    XOGL_GET_PROC(glProgramUniform3f);
    XOGL_GET_PROC(glProgramUniform3fv);
    XOGL_GET_PROC(glProgramUniform3d);
    XOGL_GET_PROC(glProgramUniform3dv);
    XOGL_GET_PROC(glProgramUniform3ui);
    XOGL_GET_PROC(glProgramUniform3uiv);
    XOGL_GET_PROC(glProgramUniform4i);
    XOGL_GET_PROC(glProgramUniform4iv);
    XOGL_GET_PROC(glProgramUniform4f);
    XOGL_GET_PROC(glProgramUniform4fv);
    XOGL_GET_PROC(glProgramUniform4d);
    XOGL_GET_PROC(glProgramUniform4dv);
    XOGL_GET_PROC(glProgramUniform4ui);
    XOGL_GET_PROC(glProgramUniform4uiv);
    XOGL_GET_PROC(glProgramUniformMatrix2fv);
    XOGL_GET_PROC(glProgramUniformMatrix3fv);
    XOGL_GET_PROC(glProgramUniformMatrix4fv);
    XOGL_GET_PROC(glProgramUniformMatrix2dv);
    XOGL_GET_PROC(glProgramUniformMatrix3dv);
    XOGL_GET_PROC(glProgramUniformMatrix4dv);
    XOGL_GET_PROC(glProgramUniformMatrix2x3fv);
    XOGL_GET_PROC(glProgramUniformMatrix3x2fv);
    XOGL_GET_PROC(glProgramUniformMatrix2x4fv);
    XOGL_GET_PROC(glProgramUniformMatrix4x2fv);
    XOGL_GET_PROC(glProgramUniformMatrix3x4fv);
    XOGL_GET_PROC(glProgramUniformMatrix4x3fv);
    XOGL_GET_PROC(glProgramUniformMatrix2x3dv);
    XOGL_GET_PROC(glProgramUniformMatrix3x2dv);
    XOGL_GET_PROC(glProgramUniformMatrix2x4dv);
    XOGL_GET_PROC(glProgramUniformMatrix4x2dv);
    XOGL_GET_PROC(glProgramUniformMatrix3x4dv);
    XOGL_GET_PROC(glProgramUniformMatrix4x3dv);
    XOGL_GET_PROC(glValidateProgramPipeline);
    XOGL_GET_PROC(glGetProgramPipelineInfoLog);
    XOGL_GET_PROC(glVertexAttribL1d);
    XOGL_GET_PROC(glVertexAttribL2d);
    XOGL_GET_PROC(glVertexAttribL3d);
    XOGL_GET_PROC(glVertexAttribL4d);
    XOGL_GET_PROC(glVertexAttribL1dv);
    XOGL_GET_PROC(glVertexAttribL2dv);
    XOGL_GET_PROC(glVertexAttribL3dv);
    XOGL_GET_PROC(glVertexAttribL4dv);
    XOGL_GET_PROC(glVertexAttribLPointer);
    XOGL_GET_PROC(glGetVertexAttribLdv);
    XOGL_GET_PROC(glViewportArrayv);
    XOGL_GET_PROC(glViewportIndexedf);
    XOGL_GET_PROC(glViewportIndexedfv);
    XOGL_GET_PROC(glScissorArrayv);
    XOGL_GET_PROC(glScissorIndexed);
    XOGL_GET_PROC(glScissorIndexedv);
    XOGL_GET_PROC(glDepthRangeArrayv);
    XOGL_GET_PROC(glDepthRangeIndexed);
    XOGL_GET_PROC(glGetFloati_v);
    XOGL_GET_PROC(glGetDoublei_v);
    XOGL_GET_PROC(glDrawArraysInstancedBaseInstance);
    XOGL_GET_PROC(glDrawElementsInstancedBaseInstance);
    XOGL_GET_PROC(glDrawElementsInstancedBaseVertexBaseInstance);
    XOGL_GET_PROC(glGetInternalformativ);
    XOGL_GET_PROC(glGetActiveAtomicCounterBufferiv);
    XOGL_GET_PROC(glBindImageTexture);
    XOGL_GET_PROC(glMemoryBarrier);
    XOGL_GET_PROC(glTexStorage1D);
    XOGL_GET_PROC(glTexStorage2D);
    XOGL_GET_PROC(glTexStorage3D);
    XOGL_GET_PROC(glDrawTransformFeedbackInstanced);
    XOGL_GET_PROC(glDrawTransformFeedbackStreamInstanced);
    XOGL_GET_PROC(glClearBufferData);
    XOGL_GET_PROC(glClearBufferSubData);
    XOGL_GET_PROC(glDispatchCompute);
    XOGL_GET_PROC(glDispatchComputeIndirect);
    XOGL_GET_PROC(glCopyImageSubData);
    XOGL_GET_PROC(glFramebufferParameteri);
    XOGL_GET_PROC(glGetFramebufferParameteriv);
    XOGL_GET_PROC(glGetInternalformati64v);
    XOGL_GET_PROC(glInvalidateTexSubImage);
    XOGL_GET_PROC(glInvalidateTexImage);
    XOGL_GET_PROC(glInvalidateBufferSubData);
    XOGL_GET_PROC(glInvalidateBufferData);
    XOGL_GET_PROC(glInvalidateFramebuffer);
    XOGL_GET_PROC(glInvalidateSubFramebuffer);
    XOGL_GET_PROC(glMultiDrawArraysIndirect);
    XOGL_GET_PROC(glMultiDrawElementsIndirect);
    XOGL_GET_PROC(glGetProgramInterfaceiv);
    XOGL_GET_PROC(glGetProgramResourceIndex);
    XOGL_GET_PROC(glGetProgramResourceName);
    XOGL_GET_PROC(glGetProgramResourceiv);
    XOGL_GET_PROC(glGetProgramResourceLocation);
    XOGL_GET_PROC(glGetProgramResourceLocationIndex);
    XOGL_GET_PROC(glShaderStorageBlockBinding);
    XOGL_GET_PROC(glTexBufferRange);
    XOGL_GET_PROC(glTexStorage2DMultisample);
    XOGL_GET_PROC(glTexStorage3DMultisample);
    XOGL_GET_PROC(glTextureView);
    XOGL_GET_PROC(glBindVertexBuffer);
    XOGL_GET_PROC(glVertexAttribFormat);
    XOGL_GET_PROC(glVertexAttribIFormat);
    XOGL_GET_PROC(glVertexAttribLFormat);
    XOGL_GET_PROC(glVertexAttribBinding);
    XOGL_GET_PROC(glVertexBindingDivisor);
    XOGL_GET_PROC(glDebugMessageControl);
    XOGL_GET_PROC(glDebugMessageInsert);
    XOGL_GET_PROC(glDebugMessageCallback);
    XOGL_GET_PROC(glGetDebugMessageLog);
    XOGL_GET_PROC(glPushDebugGroup);
    XOGL_GET_PROC(glPopDebugGroup);
    XOGL_GET_PROC(glObjectLabel);
    XOGL_GET_PROC(glGetObjectLabel);
    XOGL_GET_PROC(glObjectPtrLabel);
    XOGL_GET_PROC(glGetObjectPtrLabel);
    XOGL_GET_PROC(glBufferStorage);
    XOGL_GET_PROC(glClearTexImage);
    XOGL_GET_PROC(glClearTexSubImage);
    XOGL_GET_PROC(glBindBuffersBase);
    XOGL_GET_PROC(glBindBuffersRange);
    XOGL_GET_PROC(glBindTextures);
    XOGL_GET_PROC(glBindSamplers);
    XOGL_GET_PROC(glBindImageTextures);
    XOGL_GET_PROC(glBindVertexBuffers);
    XOGL_GET_PROC(glClipControl);
    XOGL_GET_PROC(glCreateTransformFeedbacks);
    XOGL_GET_PROC(glTransformFeedbackBufferBase);
    XOGL_GET_PROC(glTransformFeedbackBufferRange);
    XOGL_GET_PROC(glGetTransformFeedbackiv);
    XOGL_GET_PROC(glGetTransformFeedbacki_v);
    XOGL_GET_PROC(glGetTransformFeedbacki64_v);
    XOGL_GET_PROC(glCreateBuffers);
    XOGL_GET_PROC(glNamedBufferStorage);
    XOGL_GET_PROC(glNamedBufferData);
    XOGL_GET_PROC(glNamedBufferSubData);
    XOGL_GET_PROC(glCopyNamedBufferSubData);
    XOGL_GET_PROC(glClearNamedBufferData);
    XOGL_GET_PROC(glClearNamedBufferSubData);
    XOGL_GET_PROC(glUnmapNamedBuffer);
    XOGL_GET_PROC(glFlushMappedNamedBufferRange);
    XOGL_GET_PROC(glGetNamedBufferParameteriv);
    XOGL_GET_PROC(glGetNamedBufferParameteri64v);
    XOGL_GET_PROC(glGetNamedBufferPointerv);
    XOGL_GET_PROC(glGetNamedBufferSubData);
    XOGL_GET_PROC(glCreateFramebuffers);
    XOGL_GET_PROC(glNamedFramebufferRenderbuffer);
    XOGL_GET_PROC(glNamedFramebufferParameteri);
    XOGL_GET_PROC(glNamedFramebufferTexture);
    XOGL_GET_PROC(glNamedFramebufferTextureLayer);
    XOGL_GET_PROC(glNamedFramebufferDrawBuffer);
    XOGL_GET_PROC(glNamedFramebufferDrawBuffers);
    XOGL_GET_PROC(glNamedFramebufferReadBuffer);
    XOGL_GET_PROC(glInvalidateNamedFramebufferData);
    XOGL_GET_PROC(glInvalidateNamedFramebufferSubData);
    XOGL_GET_PROC(glClearNamedFramebufferiv);
    XOGL_GET_PROC(glClearNamedFramebufferuiv);
    XOGL_GET_PROC(glClearNamedFramebufferfv);
    XOGL_GET_PROC(glClearNamedFramebufferfi);
    XOGL_GET_PROC(glBlitNamedFramebuffer);
    XOGL_GET_PROC(glCheckNamedFramebufferStatus);
    XOGL_GET_PROC(glGetNamedFramebufferParameteriv);
    XOGL_GET_PROC(glGetNamedFramebufferAttachmentParameteriv);
    XOGL_GET_PROC(glCreateRenderbuffers);
    XOGL_GET_PROC(glNamedRenderbufferStorage);
    XOGL_GET_PROC(glNamedRenderbufferStorageMultisample);
    XOGL_GET_PROC(glGetNamedRenderbufferParameteriv);
    XOGL_GET_PROC(glCreateTextures);
    XOGL_GET_PROC(glTextureBuffer);
    XOGL_GET_PROC(glTextureBufferRange);
    XOGL_GET_PROC(glTextureStorage1D);
    XOGL_GET_PROC(glTextureStorage2D);
    XOGL_GET_PROC(glTextureStorage3D);
    XOGL_GET_PROC(glTextureStorage2DMultisample);
    XOGL_GET_PROC(glTextureStorage3DMultisample);
    XOGL_GET_PROC(glTextureSubImage1D);
    XOGL_GET_PROC(glTextureSubImage2D);
    XOGL_GET_PROC(glTextureSubImage3D);
    XOGL_GET_PROC(glCompressedTextureSubImage1D);
    XOGL_GET_PROC(glCompressedTextureSubImage2D);
    XOGL_GET_PROC(glCompressedTextureSubImage3D);
    XOGL_GET_PROC(glCopyTextureSubImage1D);
    XOGL_GET_PROC(glCopyTextureSubImage2D);
    XOGL_GET_PROC(glCopyTextureSubImage3D);
    XOGL_GET_PROC(glTextureParameterf);
    XOGL_GET_PROC(glTextureParameterfv);
    XOGL_GET_PROC(glTextureParameteri);
    XOGL_GET_PROC(glTextureParameterIiv);
    XOGL_GET_PROC(glTextureParameterIuiv);
    XOGL_GET_PROC(glTextureParameteriv);
    XOGL_GET_PROC(glGenerateTextureMipmap);
    XOGL_GET_PROC(glBindTextureUnit);
    XOGL_GET_PROC(glGetTextureImage);
    XOGL_GET_PROC(glGetCompressedTextureImage);
    XOGL_GET_PROC(glGetTextureLevelParameterfv);
    XOGL_GET_PROC(glGetTextureLevelParameteriv);
    XOGL_GET_PROC(glGetTextureParameterfv);
    XOGL_GET_PROC(glGetTextureParameterIiv);
    XOGL_GET_PROC(glGetTextureParameterIuiv);
    XOGL_GET_PROC(glGetTextureParameteriv);
    XOGL_GET_PROC(glCreateVertexArrays);
    XOGL_GET_PROC(glDisableVertexArrayAttrib);
    XOGL_GET_PROC(glEnableVertexArrayAttrib);
    XOGL_GET_PROC(glVertexArrayElementBuffer);
    XOGL_GET_PROC(glVertexArrayVertexBuffer);
    XOGL_GET_PROC(glVertexArrayVertexBuffers);
    XOGL_GET_PROC(glVertexArrayAttribBinding);
    XOGL_GET_PROC(glVertexArrayAttribFormat);
    XOGL_GET_PROC(glVertexArrayAttribIFormat);
    XOGL_GET_PROC(glVertexArrayAttribLFormat);
    XOGL_GET_PROC(glVertexArrayBindingDivisor);
    XOGL_GET_PROC(glGetVertexArrayiv);
    XOGL_GET_PROC(glGetVertexArrayIndexediv);
    XOGL_GET_PROC(glGetVertexArrayIndexed64iv);
    XOGL_GET_PROC(glCreateSamplers);
    XOGL_GET_PROC(glCreateProgramPipelines);
    XOGL_GET_PROC(glCreateQueries);
    XOGL_GET_PROC(glGetQueryBufferObjecti64v);
    XOGL_GET_PROC(glGetQueryBufferObjectiv);
    XOGL_GET_PROC(glGetQueryBufferObjectui64v);
    XOGL_GET_PROC(glGetQueryBufferObjectuiv);
    XOGL_GET_PROC(glMemoryBarrierByRegion);
    XOGL_GET_PROC(glGetTextureSubImage);
    XOGL_GET_PROC(glGetCompressedTextureSubImage);
    XOGL_GET_PROC(glGetGraphicsResetStatus);
    XOGL_GET_PROC(glGetnCompressedTexImage);
    XOGL_GET_PROC(glGetnTexImage);
    XOGL_GET_PROC(glGetnUniformdv);
    XOGL_GET_PROC(glGetnUniformfv);
    XOGL_GET_PROC(glGetnUniformiv);
    XOGL_GET_PROC(glGetnUniformuiv);
    XOGL_GET_PROC(glReadnPixels);
    XOGL_GET_PROC(glTextureBarrier);
    XOGL_GET_PROC(glGetTextureHandleARB);
    XOGL_GET_PROC(glGetTextureSamplerHandleARB);
    XOGL_GET_PROC(glMakeTextureHandleResidentARB);
    XOGL_GET_PROC(glMakeTextureHandleNonResidentARB);
    XOGL_GET_PROC(glGetImageHandleARB);
    XOGL_GET_PROC(glMakeImageHandleResidentARB);
    XOGL_GET_PROC(glMakeImageHandleNonResidentARB);
    XOGL_GET_PROC(glUniformHandleui64ARB);
    XOGL_GET_PROC(glUniformHandleui64vARB);
    XOGL_GET_PROC(glProgramUniformHandleui64ARB);
    XOGL_GET_PROC(glProgramUniformHandleui64vARB);
    XOGL_GET_PROC(glIsTextureHandleResidentARB);
    XOGL_GET_PROC(glIsImageHandleResidentARB);
    XOGL_GET_PROC(glVertexAttribL1ui64ARB);
    XOGL_GET_PROC(glVertexAttribL1ui64vARB);
    XOGL_GET_PROC(glGetVertexAttribLui64vARB);
    XOGL_GET_PROC(glCreateSyncFromCLeventARB);
    XOGL_GET_PROC(glDispatchComputeGroupSizeARB);
    XOGL_GET_PROC(glDebugMessageControlARB);
    XOGL_GET_PROC(glDebugMessageInsertARB);
    XOGL_GET_PROC(glDebugMessageCallbackARB);
    XOGL_GET_PROC(glGetDebugMessageLogARB);
    XOGL_GET_PROC(glBlendEquationiARB);
    XOGL_GET_PROC(glBlendEquationSeparateiARB);
    XOGL_GET_PROC(glBlendFunciARB);
    XOGL_GET_PROC(glBlendFuncSeparateiARB);
    XOGL_GET_PROC(glMultiDrawArraysIndirectCountARB);
    XOGL_GET_PROC(glMultiDrawElementsIndirectCountARB);
    XOGL_GET_PROC(glGetGraphicsResetStatusARB);
    XOGL_GET_PROC(glGetnTexImageARB);
    XOGL_GET_PROC(glReadnPixelsARB);
    XOGL_GET_PROC(glGetnCompressedTexImageARB);
    XOGL_GET_PROC(glGetnUniformfvARB);
    XOGL_GET_PROC(glGetnUniformivARB);
    XOGL_GET_PROC(glGetnUniformuivARB);
    XOGL_GET_PROC(glGetnUniformdvARB);
    XOGL_GET_PROC(glMinSampleShadingARB);
    XOGL_GET_PROC(glNamedStringARB);
    XOGL_GET_PROC(glDeleteNamedStringARB);
    XOGL_GET_PROC(glCompileShaderIncludeARB);
    XOGL_GET_PROC(glIsNamedStringARB);
    XOGL_GET_PROC(glGetNamedStringARB);
    XOGL_GET_PROC(glGetNamedStringivARB);
    XOGL_GET_PROC(glBufferPageCommitmentARB);
    XOGL_GET_PROC(glNamedBufferPageCommitmentEXT);
    XOGL_GET_PROC(glNamedBufferPageCommitmentARB);
    XOGL_GET_PROC(glTexPageCommitmentARB);


    return 0;
}

void xogl_swapBuffers(Display* disp, Window win) {
    xogl_context_swapBuffers(disp, win);
}

void xogl_destroy(Display* disp) {
    xogl_context_destroy(disp);
}
